image: registry.gitlab.com/7up-tv/backend:latest

stages:
  - deploy

staging:
  stage: deploy
  script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Run Envoy
    - ~/.composer/vendor/bin/envoy run deploy_staging
  environment:
    name: staging
    url: https://7up.tv
  only:
    - master
